apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-multi-tenant-proxy
  namespace: default
data:
  PROMETHEUS_MULTI_TENANT_PROXY_PROMETHEUS_ENDPOINT: http://prometheus-operated.default.svc.cluster.local:9090
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    application: prometheus-multi-tenant-proxy
  name: prometheus-auth-config
  namespace: default
data:
  authn.yaml: dXNlcnM6CiAgLSB1c2VybmFtZTogSGFwcHkKICAgIHBhc3N3b3JkOiBQcm9tZXRoZXVzCiAgICBuYW1lc3BhY2U6IGRlZmF1bHQKICAtIHVzZXJuYW1lOiBTYWQKICAgIHBhc3N3b3JkOiBQcm9tZXRoZXVzCiAgICBuYW1lc3BhY2U6IGt1YmUtc3lzdGVtCg==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: prometheus-multi-tenant-proxy
  name: prometheus-multi-tenant-proxy
  namespace: default
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      application: prometheus-multi-tenant-proxy
  template:
    metadata:
      labels:
        application: prometheus-multi-tenant-proxy
    spec:
      volumes:
      - name: prometheus-auth-config
        secret:
          secretName: prometheus-auth-config
      containers:
      - name: prometheus-multi-tenant-proxy
        image: ghcr.io/k8spin/prometheus-multi-tenant-proxy:latest
        imagePullPolicy: Always
        command: ["/bin/bash"]
        args: ["-c", "/prometheus-multi-tenant-proxy run --port=9092 --prometheus-endpoint=${PROMETHEUS_MULTI_TENANT_PROXY_PROMETHEUS_ENDPOINT} --auth-config=/etc/prometheus-auth-config/authn.yaml"]
        ports:
          - name: http
            containerPort: 9092
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: 9092
        readinessProbe:
          httpGet:
            path: /-/ready
            port: 9092
        envFrom:
        - configMapRef:
            name: prometheus-multi-tenant-proxy
        volumeMounts:
          - name: prometheus-auth-config
            mountPath: /etc/prometheus-auth-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-multi-tenant-proxy
  namespace: default
  labels:
    application: prometheus-multi-tenant-proxy
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 9092
    protocol: TCP
    targetPort: http
  selector:
    application: prometheus-multi-tenant-proxy
