{{- if .Values.proxy.auth.basic.createSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "prometheus-multi-tenant-proxy.labels" . | nindent 4 }}
  name: {{ include "prometheus-multi-tenant-proxy.fullname" . }}
data:
  # Values contains a key containing a multiline string, so we need to base64 encode it
  # In case the key is not present or empty, we need to provide an empty users list
  # to avoid a YAML error
  authn.yaml:
    {{- if .Values.proxy.auth.basic.authn }}
      {{ .Values.proxy.auth.basic.authn | b64enc }}
    {{- else }}
      {{ print "users: []" | b64enc }}
    {{- end }}
{{- end }}