name: "Tests"

on:
  push:
    branches:
      - "*"

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v4
      with:
        go-version: '1.20.5'

    - name: Unit tests
      run: go test -v ./...

    - run: |
        export VERSION=${GITHUB_SHA::8}
        echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV
        export CURRENT_DATE=$(date --iso-8601=seconds)
        echo "RELEASE_DATE=$CURRENT_DATE" >> $GITHUB_ENV

    - name: Building binaries
      run: |
        go mod download
        mkdir binaries
        cd cmd/prometheus-multi-tenant-proxy
        GOOS=darwin GOARCH=amd64 go build -o prometheus-multi-tenant-proxy -ldflags="-X 'main.version=${{ env.RELEASE_VERSION }}' -X 'main.commit=${{ github.sha }}' -X 'main.date=${{ env.RELEASE_DATE }}'"
        mv prometheus-multi-tenant-proxy ../../binaries/prometheus-multi-tenant-proxy-darwing-amd64
        GOOS=linux GOARCH=amd64 go build -o prometheus-multi-tenant-proxy -ldflags="-X 'main.version=${{ env.RELEASE_VERSION }}' -X 'main.commit=${{ github.sha }}' -X 'main.date=${{ env.RELEASE_DATE }}'"
        mv prometheus-multi-tenant-proxy ../../binaries/prometheus-multi-tenant-proxy-linux-amd64

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        file: ./build/package/Dockerfile
        context: .
        platforms: linux/amd64,linux/arm/v7,linux/arm64
        pull: true
        no-cache: true
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:${{ env.RELEASE_VERSION }}
        build-args: |
          RELEASE_DATE=${{ env.RELEASE_DATE }}
          VERSION=${{ env.RELEASE_VERSION }}
          COMMIT=${{ github.sha }}
    - name: Publish Unstable Helm charts
      uses: stefanprodan/helm-gh-pages@v1.7.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        charts_dir: deployments/kubernetes/helm
        chart_version: 0.0.0-${{ env.RELEASE_VERSION }}
        app_version: ${{ env.RELEASE_VERSION }}
