name: "Tests"

on:
  push:
    branches:
      - "*"

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17.0'
    - run: go test -v ./...
